// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-6p9gvZ9kiuMUyLv7_nuh3R3-aSR_Ns',
    appId: '1:172684741649:web:efead14db22bab390fb5b0',
    messagingSenderId: '172684741649',
    projectId: 'hola-chat-app-8e711',
    authDomain: 'hola-chat-app-8e711.firebaseapp.com',
    storageBucket: 'hola-chat-app-8e711.appspot.com',
    measurementId: 'G-37Q706CLCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcx31aQoBErN-6A2nool5F13Kz8ElMeCA',
    appId: '1:172684741649:android:bc0623b6401b55620fb5b0',
    messagingSenderId: '172684741649',
    projectId: 'hola-chat-app-8e711',
    storageBucket: 'hola-chat-app-8e711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm9btS4N5YJXO00LF9lyoAgzkarhrlOFQ',
    appId: '1:172684741649:ios:0e18236ffcea4ee70fb5b0',
    messagingSenderId: '172684741649',
    projectId: 'hola-chat-app-8e711',
    storageBucket: 'hola-chat-app-8e711.appspot.com',
    iosClientId: '172684741649-0thu0vp8t20kv36alv9rd8hpc1bts16r.apps.googleusercontent.com',
    iosBundleId: 'com.example.holaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm9btS4N5YJXO00LF9lyoAgzkarhrlOFQ',
    appId: '1:172684741649:ios:0e18236ffcea4ee70fb5b0',
    messagingSenderId: '172684741649',
    projectId: 'hola-chat-app-8e711',
    storageBucket: 'hola-chat-app-8e711.appspot.com',
    iosClientId: '172684741649-0thu0vp8t20kv36alv9rd8hpc1bts16r.apps.googleusercontent.com',
    iosBundleId: 'com.example.holaChat',
  );
}
